blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://coretalk.space/tags/cip
    about: Share your CIP comments in Talk \#CIP
  - name: Security Bugs
    url: https://dev.coreblockchain.cc/report-bug/
    about: Please report security vulnerabilities here.
