blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/core-coin/cip/discussions/categories/cip
    about: Share your CIP comments in Discussions — CIPs
  - name: Security Bugs
    url: https://dev.coreblockchain.net/report-bug/
    about: Please report security vulnerabilities here.
