name: Create new CIP
description: Create a new CIP draft
title: "[CIP] "
labels:
  - cip
  - draft
assignees:
  - rastislavcore
body:
  - type: markdown
    attributes:
      value: |
        This is the suggested template for new CIPs. Note that a CIP number will be assigned by an editor. When opening a pull request to submit your CIP, use an abbreviated title in the filename, `cip-ID.md`, where "ID" is the CIP ID. The title should be 44 characters or fewer.

  - type: dropdown
    id: lang
    attributes:
      label: Language
      options:
        - en-US
        - en-GB
        - en-IE
        - en-CA
        - en-AU
        - en-NZ
        - en-ZA
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: CIP categories
      multiple: false
      options:
        - core
        - networking
        - interface
        - cbc
        - meta
        - informational
    validations:
      required: true

  - type: input
    id: abstract
    attributes:
      label: Abstract
      description: A short (~200 words) description of the technical issue being addressed.
      placeholder: Abstract
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: The motivation is crucial for CIPs that aim to change the Core protocol. Clearly explain why the existing protocol specification is inadequate to address the problem the CIP aims to solve. CIP submissions lacking sufficient motivation may be rejected outright.
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Specification
      description: The technical specification should detail the syntax and semantics of any new feature. This section should be detailed enough to allow for competing, interoperable implementations on all current Core platforms.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: The rationale elaborates on the specification, discussing the motivations behind the design and reasons for specific design decisions. Discuss alternative designs considered and any related work. The rationale may also provide evidence of community consensus and should address significant objections or concerns raised during discussions.
    validations:
      required: true

  - type: textarea
    id: backwards-compatibility
    attributes:
      label: Backwards Compatibility
      description: All CIPs introducing backward incompatibilities must include a section detailing these incompatibilities and their severity. The CIP should explain how the author proposes to address these incompatibilities. CIP submissions without a comprehensive backward compatibility analysis may be rejected outright.
    validations:
      required: false

  - type: textarea
    id: test-cases
    attributes:
      label: Test Cases
      description: Test cases for implementation are mandatory for CIPs that affect consensus changes. Other CIPs may choose to include links to relevant test cases, if applicable.
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Implementations should be finalized before any CIP receives "Final" status, but they don't need to be completed before the CIP is accepted. While there's merit in achieving consensus on the specification and rationale before coding, the principle of "rough consensus and running code" remains useful for resolving many API details discussions.
    validations:
      required: false

  - type: textarea
    id: security-considerations
    attributes:
      label: Security Considerations
      description: All CIPs must include a section discussing the security implications and considerations relevant to the proposed change. Highlight risks and provide details crucial for security discussions. CIP submissions without the "Security Considerations" section will be rejected. A CIP cannot achieve "Final" status without a satisfactory Security Considerations discussion, as determined by the reviewers.
    validations:
      required: false

  - type: input
    id: requires
    attributes:
      label: Requires
      description: CIP number(s)
      placeholder: Requires
    validations:
      required: false

  - type: input
    id: replaces
    attributes:
      label: Replaces
      description: CIP number(s)
      placeholder: Replaces
    validations:
      required: false

  - type: input
    id: superseded-by
    attributes:
      label: Superseded by
      description: CIP number(s)
      placeholder: Superseded by
