name: CIP linter
on:
  pull_request:
    branches:
      - master
    paths:
      - "cip/*.md"
      - "cip/*.mdx"
      - ".github/workflows/markdownlint.yml"
      - ".github/.markdownlint.json"

jobs:
  cip-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .github/.markdownlint.json
          search_paths: |
            cip/*.md
            cip/*.mdx
