name: CIP linter

on:
  pull_request:
    branches:
      - master
    paths:
      - "cip/**/*.md"
      - "cip/**/*.mdx"
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - "README.md"
      - ".github/workflows/markdownlint.yml"
      - ".github/.markdownlint.json"

jobs:
  cip-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Lint Markdown
        uses: ruzickap/action-my-markdown-linter@v1.3.1
        with:
          config_file: .github/.markdownlint.json
          search_paths: |
            README.md
            docs
            cip
